arrowParens: always
bracketSameLine: false
bracketSpacing: true
htmlWhitespaceSensitivity: css
jsxSingleQuote: false
printWidth: 80
quoteProps: as-needed
semi: true
singleAttributePerLine: false
singleQuote: true
tabWidth: 2
trailingComma: all
useTabs: false
overrides:
  - files: "*.json"
    options:
      tabWidth: 2
  - files: "*.html"
    options:
      tabWidth: 4
      